# Site settings
title: Coding Plus Tea
header-img: img/computer-bg.png
baseurl: ""
copyright_name: Isabel Vazquez
description: > # this means to ignore newlines until "baseurl:"
twitter_username: isabelvazquez__
github_username: IsabelVazquez
google_analytics: "UA-108478784-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]
