# Site settings
title: Coding Plus Tea
baseurl: ""
copyright_name: Isabel Vazquez
description: > # this means to ignore newlines until "baseurl:"
twitter_username: isabelvazquez__
linkedin: vazquezisabel
github_username: IsabelVazquez
google_analytics: "UA-108478784-1"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
include:
  - "_pages"

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Gruntfile.js
  - package.json
  - npm-debug.log
  - node_modules
  - vendor
  - bundle
  - ".bundle"
  - ".sass-cache"
  - script
  - src

plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]
