# Site settings
title: Coding Plus Tea
header-img: img/home-bg.png
email: 12ivazquez@gmail.com
copyright_name: IsabelVazquez
description: > # this means to ignore newlines until "baseurl:"
  Ramblings For The World To See (Maybe)
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  IsabelVazquez
learn_profile: IsabelVazquez
email_username: 12ivazquez@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
