#!/bin/bash

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

title "Building site"
bundle exec jekyll build --config _config.yml
